apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-app
  name: dotnet-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: 847415613895.dkr.ecr.us-east-2.amazonaws.com/my-docker-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-app
    k8s-app: dotnet-app
  name: dotnet-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: dotnet-app